# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: Default


steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'C:\Users\HP\Documents\agent_folder\vsts-agent-win-x64-4.259.0\_work\4\s'
    backendServiceArm: 'serviceconnection1'
    backendAzureRmResourceGroupName: 'rk'
    backendAzureRmStorageAccountName: 'aknkdkns'
    backendAzureRmContainerName: 'contaner'
    backendAzureRmKey: 'rupesh.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'C:\Users\HP\Documents\agent_folder\vsts-agent-win-x64-4.259.0\_work\4\s'
    environmentServiceNameAzureRM: 'serviceconnection1'

